# Site settings
title: Cascadia Urban Analytics Cooperative
email: urbandat@uw.edu
description: >
  A partnership bewteen the University of Washington and the University of British Columbia, the focus of the Cascadia Urban Analytics Cooperative is data science for social good in an urban context: high-impact data science and analytics projects that aim to understand and extract valuable actionable information out of data from urban environments in the Cascadia region.
url: "http://cascadiadata.org"
twitter_username: urbanuw
github_username:  cascadiadata
# Build settings
markdown: kramdown

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name